name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: poetry install -E messenger -E dns

    - name: Run tests
      run: poetry run pytest
